build: fix out of tree builds
---snip---
  CXX      GenefxEngine.lo
In file included from ../../../../DirectFB/src/core/Renderer.h:73:0,
                 from ../../../../DirectFB/src/gfx/generic/GenefxEngine.cpp:61:
../../../../DirectFB/src/core/Graphics.h:37:30: fatal error: core/CoreSurface.h: No such file or directory
 #include <core/CoreSurface.h>
                              ^
  CXX      EGLDisplayX11.lo
../../../DirectFB/systems/x11/EGLDisplayX11.cpp:51:26: fatal error: core/CoreDFB.h: No such file or directory
 #include <core/CoreDFB.h>
                          ^
  CXX      X11EGLImpl.lo
../../../DirectFB/systems/x11/X11EGLImpl.cpp:52:40: fatal error: core/CoreSurfaceAllocation.h: No such file or directory
 #include <core/CoreSurfaceAllocation.h>
                                        ^
  CC       default.lo
../../../DirectFB/wm/default/default.c:67:34: fatal error: core/CoreLayerRegion.h: No such file or directory
 #include <core/CoreLayerRegion.h>
                                  ^

compilation terminated.
---snap---

The files in question are autogenerated and end up below $(top_builddir), so this has
to be part of the included directories.